image: Visual Studio 2017
configuration: Release
platform: Any CPU
install:
  - choco install gitversion.portable -pre -y
before_build:
  - cmd: nuget restore DotNet\CesiumLanguageWriter.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo DotNet\CesiumLanguageWriter\Properties\AssemblyInfo.cs
build:
  project: DotNet\CesiumLanguageWriter.sln
  publish_nuget: true
  parallel: true
  verbosity: minimal