version: 2.3.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: DotNet\CesiumLanguageWriter\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: 2.3.0
before_build:
- cmd: nuget restore DotNet\CesiumLanguageWriter.sln
build:
  project: DotNet\CesiumLanguageWriter.sln
  publish_nuget: true
  parallel: true
  verbosity: minimal